version: '3.9'
services:
  db:
    image: mysql:5.7
    container_name: gm_cars_container
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3300:3300" #was 3306
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p","${DB_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: project_name_backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
          condition: service_healthy
volumes:
  data: