# Generated by Django 5.1.dev20240213134749 on 2024-02-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('miles', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
