# Generated by Django 5.0.3 on 2024-03-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMCarComparisonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('transmission', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
                ('engine', models.CharField(max_length=30)),
                ('fuel', models.CharField(max_length=30)),
                ('drive', models.CharField(max_length=5)),
                ('horsepower', models.FloatField()),
                ('mileage', models.FloatField()),
                ('color', models.CharField(max_length=30)),
                ('trim', models.CharField(max_length=30)),
                ('image', models.FilePathField()),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
